"""
disease_database.py
Complete disease knowledge base for the Crop Health Agent.
Each entry contains all agronomic details needed for diagnosis and treatment.
"""

from typing import Dict, Any

DISEASE_DATABASE: Dict[str, Dict[str, Any]] = {

    # ── TOMATO ──────────────────────────────────────────────────────────────
    "Tomato___Early_Blight": {
        "disease_name": "Early Blight",
        "scientific_name": "Alternaria solani",
        "crop": "Tomato",
        "symptoms": [
            "Dark brown circular spots with concentric rings (target-board pattern)",
            "Yellow halo surrounding lesions",
            "Lower leaves affected first, progressing upward",
            "Premature defoliation",
            "Dark sunken lesions on stem near soil line",
        ],
        "treatment": "Remove infected leaves. Apply fungicide spray every 7 days until symptoms subside.",
        "organic_treatment": "Spray neem oil (5ml/L) or copper soap solution every 7 days. Remove infected debris.",
        "chemical_treatment": "Mancozeb 75 WP @ 2g/L or Chlorothalonil 75 WP @ 2g/L. Alternate with Azoxystrobin 23 SC @ 1ml/L.",
        "recommended_fertilizer": "Balanced NPK (19:19:19) to strengthen plant immunity. Avoid excess nitrogen.",
        "recommended_pesticide": "Mancozeb 75 WP, Chlorothalonil 75 WP, Azoxystrobin 23 SC",
        "prevention": [
            "Use certified disease-free seeds.",
            "Avoid overhead irrigation; water at the base.",
            "Maintain proper plant spacing for air circulation.",
            "Rotate crops — avoid planting tomato in the same plot consecutively.",
            "Apply mulch to prevent soil splash.",
        ],
        "spread_risk": "Medium",
        "recovery_time_days": 14,
        "nutrient_deficiency": "Potassium Deficiency",
    },

    "Tomato___Late_Blight": {
        "disease_name": "Late Blight",
        "scientific_name": "Phytophthora infestans",
        "crop": "Tomato",
        "symptoms": [
            "Water-soaked, greasy-looking lesions on leaves",
            "White mold on underside of leaves in humid conditions",
            "Rapid browning and death of foliage",
            "Dark brown lesions on stems",
            "Fruit shows firm brown rot",
        ],
        "treatment": "Apply systemic fungicide immediately. Remove and destroy infected plant parts.",
        "organic_treatment": "Copper hydroxide spray (3g/L). Remove infected plants promptly.",
        "chemical_treatment": "Metalaxyl + Mancozeb (Ridomil Gold) @ 2.5g/L. Cymoxanil + Mancozeb @ 3g/L.",
        "recommended_fertilizer": "Calcium-rich fertilizer (Calcium Nitrate) to strengthen cell walls.",
        "recommended_pesticide": "Ridomil Gold MZ, Cymoxanil 8% + Mancozeb 64% WP",
        "prevention": [
            "Plant resistant varieties (Mountain Magic, Defiant).",
            "Avoid dense planting.",
            "Destroy volunteer tomato and potato plants nearby.",
            "Prophylactic copper spray before monsoon season.",
        ],
        "spread_risk": "High",
        "recovery_time_days": 21,
        "nutrient_deficiency": "Calcium Deficiency",
    },

    "Tomato___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Tomato",
        "symptoms": ["No visible disease symptoms", "Green healthy foliage", "Normal growth"],
        "treatment": "No treatment required.",
        "organic_treatment": "Continue regular neem oil preventive spray.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Continue balanced NPK schedule.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular field scouting", "Balanced irrigation", "Timely fertilisation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },

    # ── POTATO ──────────────────────────────────────────────────────────────
    "Potato___Early_Blight": {
        "disease_name": "Early Blight",
        "scientific_name": "Alternaria solani",
        "crop": "Potato",
        "symptoms": [
            "Small dark brown spots with concentric rings on older leaves",
            "Yellow tissue surrounding lesions",
            "Defoliation starting from lower canopy",
            "Tuber surface shows dark, slightly sunken lesions",
        ],
        "treatment": "Apply fungicide at first sign. Remove infected foliage.",
        "organic_treatment": "Neem oil spray (5ml/L) every 10 days. Compost tea foliar spray.",
        "chemical_treatment": "Mancozeb 75 WP @ 2g/L or Iprodione 50 WP @ 2g/L every 7–10 days.",
        "recommended_fertilizer": "Potassium Sulphate to improve tuber quality and disease resistance.",
        "recommended_pesticide": "Mancozeb 75 WP, Iprodione 50 WP",
        "prevention": [
            "Use certified seed tubers.",
            "Avoid excessive nitrogen fertilisation.",
            "Ensure good drainage.",
            "Rotate with non-solanaceous crops.",
        ],
        "spread_risk": "Medium",
        "recovery_time_days": 14,
        "nutrient_deficiency": "Potassium Deficiency",
    },

    "Potato___Late_Blight": {
        "disease_name": "Late Blight",
        "scientific_name": "Phytophthora infestans",
        "crop": "Potato",
        "symptoms": [
            "Dark water-soaked lesions on leaves and stems",
            "White sporulation on underside of leaves",
            "Rapid collapse of foliage in wet weather",
            "Tubers show reddish-brown granular rot",
            "Foul smell from infected tubers",
        ],
        "treatment": "Apply systemic fungicide immediately. Destroy infected haulms before harvest.",
        "organic_treatment": "Copper Oxychloride 50 WP @ 3g/L. Remove infected plants.",
        "chemical_treatment": "Metalaxyl + Mancozeb @ 2.5g/L. Dimethomorph 50 WP @ 1g/L.",
        "recommended_fertilizer": "Calcium Nitrate to strengthen cell walls and reduce infection entry.",
        "recommended_pesticide": "Ridomil Gold MZ, Dimethomorph 50 WP",
        "prevention": [
            "Plant resistant varieties (Kufri Jyoti, Kufri Bahar).",
            "Use certified blight-free seed tubers.",
            "Prophylactic spray of Chlorothalonil before monsoon.",
            "Avoid waterlogging.",
        ],
        "spread_risk": "Critical",
        "recovery_time_days": 25,
        "nutrient_deficiency": "Calcium Deficiency",
    },

    "Potato___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Potato",
        "symptoms": ["No visible disease symptoms", "Green healthy foliage", "Normal tuber development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem oil spray.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 10:26:26 at tuber initiation stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Proper hilling", "Balanced irrigation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },

    # ── CORN / MAIZE ─────────────────────────────────────────────────────────
    "Corn___Common_Rust": {
        "disease_name": "Common Rust",
        "scientific_name": "Puccinia sorghi",
        "crop": "Corn",
        "symptoms": [
            "Oval to elongated cinnamon-brown pustules on both leaf surfaces",
            "Pustules turn dark brown/black as they mature",
            "Severe infection causes premature leaf death",
            "Powdery rust-coloured spore masses",
        ],
        "treatment": "Apply fungicide at early pustule stage. Remove heavily infected leaves.",
        "organic_treatment": "Baking soda solution (5g/L) spray. Neem oil (5ml/L) every 7 days.",
        "chemical_treatment": "Propiconazole 25 EC @ 1ml/L or Tebuconazole 250 EW @ 1ml/L.",
        "recommended_fertilizer": "Balanced NPK; avoid excess nitrogen which promotes lush susceptible growth.",
        "recommended_pesticide": "Propiconazole 25 EC, Tebuconazole 250 EW",
        "prevention": [
            "Plant rust-resistant hybrids.",
            "Early planting to avoid peak rust season.",
            "Monitor fields from V6 stage onwards.",
        ],
        "spread_risk": "Medium",
        "recovery_time_days": 14,
        "nutrient_deficiency": "Phosphorus Deficiency",
    },

    "Corn___Northern_Leaf_Blight": {
        "disease_name": "Northern Leaf Blight",
        "scientific_name": "Exserohilum turcicum",
        "crop": "Corn",
        "symptoms": [
            "Long, elliptical grey-green to tan lesions (cigar-shaped)",
            "Lesions 2.5–15 cm long",
            "Dark sporulation visible in lesion centre",
            "Severe infection causes premature plant death",
        ],
        "treatment": "Apply fungicide at tasselling stage. Remove crop debris after harvest.",
        "organic_treatment": "Trichoderma-based biocontrol spray. Neem oil preventive spray.",
        "chemical_treatment": "Azoxystrobin 23 SC @ 1ml/L or Mancozeb 75 WP @ 2g/L.",
        "recommended_fertilizer": "Potassium Sulphate to improve stress tolerance.",
        "recommended_pesticide": "Azoxystrobin 23 SC, Mancozeb 75 WP",
        "prevention": [
            "Use resistant hybrids.",
            "Crop rotation with non-host crops.",
            "Deep ploughing to bury infected debris.",
        ],
        "spread_risk": "Medium",
        "recovery_time_days": 18,
        "nutrient_deficiency": "Nitrogen Deficiency",
    },

    "Corn___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Corn",
        "symptoms": ["No visible disease symptoms", "Dark green healthy leaves", "Normal ear development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Top-dress with Urea at knee-high stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Balanced fertilisation", "Proper plant spacing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },

    # ── APPLE ────────────────────────────────────────────────────────────────
    "Apple___Scab": {
        "disease_name": "Apple Scab",
        "scientific_name": "Venturia inaequalis",
        "crop": "Apple",
        "symptoms": [
            "Olive-green to brown velvety spots on leaves",
            "Scabby, corky lesions on fruit surface",
            "Distorted, cracked fruit",
            "Premature leaf and fruit drop",
        ],
        "treatment": "Apply fungicide from green tip stage. Remove fallen leaves.",
        "organic_treatment": "Lime sulphur spray at dormant stage. Copper spray at green tip.",
        "chemical_treatment": "Captan 50 WP @ 2g/L or Myclobutanil 10 WP @ 1g/L every 7–10 days.",
        "recommended_fertilizer": "Balanced NPK with micronutrients (Zinc, Boron).",
        "recommended_pesticide": "Captan 50 WP, Myclobutanil 10 WP, Dodine 65 WP",
        "prevention": [
            "Plant scab-resistant varieties (Liberty, Enterprise).",
            "Rake and destroy fallen leaves.",
            "Prune for good air circulation.",
            "Apply dormant lime sulphur spray.",
        ],
        "spread_risk": "High",
        "recovery_time_days": 21,
        "nutrient_deficiency": "Zinc Deficiency",
    },

    "Apple___Black_Rot": {
        "disease_name": "Black Rot",
        "scientific_name": "Botryosphaeria obtusa",
        "crop": "Apple",
        "symptoms": [
            "Purple spots on leaves enlarging to brown with purple border",
            "Fruit shows brown rot starting at calyx end",
            "Fruit mummifies and turns black",
            "Cankers on branches with reddish-brown discolouration",
        ],
        "treatment": "Prune infected branches. Apply fungicide. Remove mummified fruit.",
        "organic_treatment": "Copper-based spray. Remove all mummified fruit and dead wood.",
        "chemical_treatment": "Captan 50 WP @ 2g/L or Thiophanate-methyl 70 WP @ 1.5g/L.",
        "recommended_fertilizer": "Calcium Nitrate foliar spray to strengthen fruit skin.",
        "recommended_pesticide": "Captan 50 WP, Thiophanate-methyl 70 WP",
        "prevention": [
            "Prune dead and diseased wood annually.",
            "Remove mummified fruit from trees and ground.",
            "Avoid wounding bark during cultivation.",
        ],
        "spread_risk": "Medium",
        "recovery_time_days": 30,
        "nutrient_deficiency": "Calcium Deficiency",
    },

    "Apple___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Apple",
        "symptoms": ["No visible disease symptoms", "Healthy green foliage", "Normal fruit development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive copper spray at dormant stage.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 12:32:16 at fruit set stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Annual pruning", "Regular scouting", "Balanced irrigation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },

    # ── GRAPE ────────────────────────────────────────────────────────────────
    "Grape___Black_Rot": {
        "disease_name": "Black Rot",
        "scientific_name": "Guignardia bidwellii",
        "crop": "Grape",
        "symptoms": [
            "Tan to brown circular leaf spots with dark border",
            "Small black pycnidia (fruiting bodies) in lesion centre",
            "Berries shrivel and turn black (mummify)",
            "Infected shoots show dark elongated cankers",
        ],
        "treatment": "Apply fungicide from bud break. Remove mummified berries.",
        "organic_treatment": "Copper hydroxide spray (3g/L) from bud break every 10 days.",
        "chemical_treatment": "Myclobutanil 10 WP @ 1g/L or Mancozeb 75 WP @ 2g/L from bud break.",
        "recommended_fertilizer": "Potassium Sulphate to improve berry quality and disease resistance.",
        "recommended_pesticide": "Myclobutanil 10 WP, Mancozeb 75 WP, Captan 50 WP",
        "prevention": [
            "Remove and destroy mummified berries and infected canes.",
            "Prune for good air circulation.",
            "Apply dormant copper spray.",
            "Avoid overhead irrigation.",
        ],
        "spread_risk": "High",
        "recovery_time_days": 21,
        "nutrient_deficiency": "Potassium Deficiency",
    },

    "Grape___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Grape",
        "symptoms": ["No visible disease symptoms", "Healthy green foliage", "Normal berry development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive copper spray at bud break.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 13:0:45 at berry development stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Annual pruning", "Regular scouting", "Canopy management"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },

    # ── PEPPER ───────────────────────────────────────────────────────────────
    "Pepper___Bacterial_Spot": {
        "disease_name": "Bacterial Spot",
        "scientific_name": "Xanthomonas campestris pv. vesicatoria",
        "crop": "Pepper",
        "symptoms": [
            "Small water-soaked spots on leaves turning brown",
            "Spots with yellow halo",
            "Raised scabby lesions on fruit",
            "Defoliation in severe cases",
            "Fruit drop",
        ],
        "treatment": "Apply copper bactericide. Remove infected plant material.",
        "organic_treatment": "Copper Oxychloride 50 WP @ 3g/L spray every 7 days.",
        "chemical_treatment": "Copper Hydroxide 77 WP @ 2g/L or Streptomycin Sulphate @ 200ppm.",
        "recommended_fertilizer": "Calcium Nitrate to strengthen cell walls against bacterial entry.",
        "recommended_pesticide": "Copper Hydroxide 77 WP, Streptomycin Sulphate + Copper Oxychloride",
        "prevention": [
            "Use certified disease-free transplants.",
            "Avoid overhead irrigation.",
            "Rotate with non-solanaceous crops.",
            "Disinfect tools between plants.",
        ],
        "spread_risk": "Medium",
        "recovery_time_days": 16,
        "nutrient_deficiency": "Calcium Deficiency",
    },

    "Pepper___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Pepper",
        "symptoms": ["No visible disease symptoms", "Healthy green foliage", "Normal fruit set"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem oil spray.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 19:19:19 at flowering stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Balanced irrigation", "Proper spacing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },

    # ── ADDITIONAL CROP HEALTHY ENTRIES ──────────────────────────────────────────────
    "Rice___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Rice",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal tiller development", "Upright healthy panicles"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Urea top-dressing at tillering and panicle initiation stages.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular field scouting", "Balanced NPK fertilisation", "Proper water management"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Wheat___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Wheat",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal stem and ear development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem-based seed treatment.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Urea top-dressing at crown root initiation stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Timely sowing", "Balanced fertilisation", "Regular scouting"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Maize___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Maize",
        "symptoms": ["No visible disease symptoms", "Dark green healthy leaves", "Normal ear and tassel development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Top-dress with Urea at knee-high stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Balanced fertilisation", "Proper plant spacing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Onion___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Onion",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal bulb development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem oil spray.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Potassium Sulphate at bulb initiation stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Avoid overhead irrigation", "Crop rotation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Cotton___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Cotton",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal boll development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem oil spray.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 20:10:10 at squaring stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Balanced fertilisation", "Proper spacing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Soybean___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Soybean",
        "symptoms": ["No visible disease symptoms", "Healthy trifoliate leaves", "Normal pod development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Rhizobium seed inoculation for nitrogen fixation.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Phosphorus and Potassium at sowing; minimal nitrogen.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Crop rotation", "Balanced irrigation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Banana___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Banana",
        "symptoms": ["No visible disease symptoms", "Healthy broad green leaves", "Normal bunch development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem cake soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 13:0:45 at bunch emergence stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Proper drainage", "Use tissue-culture plants"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Chilli___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Chilli",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal fruit set and development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem oil spray.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 19:19:19 at flowering stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Avoid waterlogging", "Proper spacing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Groundnut___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Groundnut",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal peg and pod development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Gypsum application at pegging stage for calcium.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Crop rotation", "Balanced irrigation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Sugarcane___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Sugarcane",
        "symptoms": ["No visible disease symptoms", "Healthy green cane leaves", "Normal stalk development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma soil drench.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Split Urea application at 30, 60, and 90 days after planting.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Use disease-free setts", "Regular scouting", "Proper drainage"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Turmeric___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Turmeric",
        "symptoms": ["No visible disease symptoms", "Healthy broad green leaves", "Normal rhizome development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem cake soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 60:50:120 kg/ha split over growing season.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Use disease-free rhizomes", "Crop rotation", "Proper drainage"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Mango___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Mango",
        "symptoms": ["No visible disease symptoms", "Healthy dark green leaves", "Normal flowering and fruit development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive copper spray before flowering.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 100:50:100 g per tree per year.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Annual pruning", "Regular scouting", "Balanced irrigation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Coconut___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Coconut",
        "symptoms": ["No visible disease symptoms", "Healthy green fronds", "Normal nut development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive neem cake soil application.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "NPK 500:320:1200 g per palm per year.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Proper drainage", "Balanced fertilisation"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Jowar___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Jowar",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal panicle development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma seed treatment.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Urea top-dressing at knee-high stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Balanced fertilisation", "Timely sowing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
    "Bajra___Healthy": {
        "disease_name": "Healthy",
        "scientific_name": "N/A",
        "crop": "Bajra",
        "symptoms": ["No visible disease symptoms", "Healthy green leaves", "Normal ear head development"],
        "treatment": "No treatment required.",
        "organic_treatment": "Preventive Trichoderma seed treatment.",
        "chemical_treatment": "No chemical treatment needed.",
        "recommended_fertilizer": "Urea top-dressing at tillering stage.",
        "recommended_pesticide": "No pesticide needed.",
        "prevention": ["Regular scouting", "Balanced fertilisation", "Timely sowing"],
        "spread_risk": "None",
        "recovery_time_days": 0,
        "nutrient_deficiency": "None",
    },
}

# Ordered list of class labels matching PlantVillage dataset folder names
CLASS_LABELS = [
    "Apple___Black_Rot",
    "Apple___Healthy",
    "Apple___Scab",
    "Corn___Common_Rust",
    "Corn___Healthy",
    "Corn___Northern_Leaf_Blight",
    "Grape___Black_Rot",
    "Grape___Healthy",
    "Pepper___Bacterial_Spot",
    "Pepper___Healthy",
    "Potato___Early_Blight",
    "Potato___Healthy",
    "Potato___Late_Blight",
    "Tomato___Early_Blight",
    "Tomato___Healthy",
    "Tomato___Late_Blight",
]

NUM_CLASSES = len(CLASS_LABELS)

SPREAD_RISK_SCORE = {"None": 0, "Low": 1, "Medium": 2, "High": 3, "Critical": 4}
